### PR TITLE
Add support for JAVA_USER variable for people who are running the tar…

### PR DESCRIPTION
**Pull request by areese**
…get jvm as someone else

### CODE REVIEW

**Comment by coderplay** [comment]
why do we introduce 2 variables here,  SUDO_USER_FLAG and JAVA_USER instead of just one of them?

**Comment by areese** [comment]
I can squish into a single flag.

**Comment by areese** [comment]
Fixed, and it now correctly works when the JAVA_USER flag isn't set, which isn't common for us.

**Comment by coderplay** [comment]
LGTM! thanks for the contribution! I will merge it soon.

**Pull request merged**
